name: Banking

on:
  push:
    branches: 
    - master

jobs:
  Build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build banking
      run: |
        cd banking
        cmake -H. -B_build
        cmake --build _build
  
  Testing:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: git submodule update --init
      
    - name: Testing
      run: |
        cmake -H. -B_build
        cmake --build _build
        cd _build
        ./tests
        
  
      
